package me.firas.corebungeeapi.guild;

public enum GuildPermission {
    INVITE_MEMBER,
    KICK_MEMBER,
    PROMOTE_MEMBER,
    DEMOTE_MEMBER,
    EDIT_TAG,
    EDIT_TAG_COLOR,
    EDIT_BANNER,
    START_QUEST,
    CLAIM_QUEST_REWARD,
    EDIT_DESCRIPTION,
    REVOKE_REQUEST,
    LOCK_CHAT,
    BYPASS_LOCK_CHAT,
    MUTE_PLAYER,
    UNMUTE_PLAYER,
    EDIT_NAME,
    OFFICER_CHAT,

}
